// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function AddChannel(arg1:string):Promise<void>;

export function ConnectToAllChannels():Promise<void>;

export function ConnectToChannel(arg1:string):Promise<void>;

export function DisconnectFromAllChannels():Promise<void>;

export function DisconnectFromChannel(arg1:string):Promise<void>;

export function GetActiveChannel():Promise<string>;

export function GetBufferSize():Promise<number>;

export function GetChannelLiveStatus(arg1:string):Promise<boolean>;

export function GetChannels():Promise<Array<string>>;

export function GetConnectedChannels():Promise<Array<string>>;

export function GetCurrentViewerCount():Promise<number>;

export function GetEmoteBase64(arg1:string,arg2:main.EmoteInfo,arg3:main.Message):Promise<string>;

export function GetRecentMessages(arg1:string,arg2:number):Promise<Array<Record<string, any>>>;

export function GetTwitchConfig():Promise<main.TwitchConfig>;

export function GetViewerCount(arg1:string):Promise<number>;

export function OnBeforeClose(arg1:context.Context):Promise<boolean>;

export function RemoveChannel(arg1:string):Promise<void>;

export function SetAudioLock(arg1:boolean):Promise<void>;

export function SwitchToChannel(arg1:string):Promise<void>;

export function ToggleAudioMute():Promise<boolean>;
