// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddChannel(arg1) {
  return window['go']['main']['App']['AddChannel'](arg1);
}

export function ConnectToAllChannels() {
  return window['go']['main']['App']['ConnectToAllChannels']();
}

export function ConnectToChannel(arg1) {
  return window['go']['main']['App']['ConnectToChannel'](arg1);
}

export function DisconnectFromAllChannels() {
  return window['go']['main']['App']['DisconnectFromAllChannels']();
}

export function DisconnectFromChannel(arg1) {
  return window['go']['main']['App']['DisconnectFromChannel'](arg1);
}

export function GetActiveChannel() {
  return window['go']['main']['App']['GetActiveChannel']();
}

export function GetBufferSize() {
  return window['go']['main']['App']['GetBufferSize']();
}

export function GetChannelLiveStatus(arg1) {
  return window['go']['main']['App']['GetChannelLiveStatus'](arg1);
}

export function GetChannels() {
  return window['go']['main']['App']['GetChannels']();
}

export function GetConnectedChannels() {
  return window['go']['main']['App']['GetConnectedChannels']();
}

export function GetCurrentViewerCount() {
  return window['go']['main']['App']['GetCurrentViewerCount']();
}

export function GetEmoteBase64(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetEmoteBase64'](arg1, arg2, arg3);
}

export function GetRecentMessages(arg1, arg2) {
  return window['go']['main']['App']['GetRecentMessages'](arg1, arg2);
}

export function GetViewerCount(arg1) {
  return window['go']['main']['App']['GetViewerCount'](arg1);
}

export function OnBeforeClose(arg1) {
  return window['go']['main']['App']['OnBeforeClose'](arg1);
}

export function RemoveChannel(arg1) {
  return window['go']['main']['App']['RemoveChannel'](arg1);
}

export function SwitchToChannel(arg1) {
  return window['go']['main']['App']['SwitchToChannel'](arg1);
}
