// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddChannel(arg1) {
  return window['go']['main']['App']['AddChannel'](arg1);
}

export function ConnectToChannel(arg1) {
  return window['go']['main']['App']['ConnectToChannel'](arg1);
}

export function DisconnectFromChannel() {
  return window['go']['main']['App']['DisconnectFromChannel']();
}

export function GetActiveChannel() {
  return window['go']['main']['App']['GetActiveChannel']();
}

export function GetBufferSize() {
  return window['go']['main']['App']['GetBufferSize']();
}

export function GetChannels() {
  return window['go']['main']['App']['GetChannels']();
}

export function GetCurrentViewerCount() {
  return window['go']['main']['App']['GetCurrentViewerCount']();
}

export function GetEmoteBase64(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetEmoteBase64'](arg1, arg2, arg3);
}

export function GetRecentMessages(arg1) {
  return window['go']['main']['App']['GetRecentMessages'](arg1);
}

export function GetViewerCount(arg1) {
  return window['go']['main']['App']['GetViewerCount'](arg1);
}

export function RemoveChannel(arg1) {
  return window['go']['main']['App']['RemoveChannel'](arg1);
}
