// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddChannel(arg1:string):Promise<void>;

export function ConnectToChannel(arg1:string):Promise<void>;

export function DisconnectFromChannel():Promise<void>;

export function GetActiveChannel():Promise<string>;

export function GetBufferSize():Promise<number>;

export function GetChannels():Promise<Array<string>>;

export function GetCurrentViewerCount():Promise<number>;

export function GetEmoteBase64(arg1:string,arg2:main.EmoteInfo,arg3:main.Message):Promise<string>;

export function GetRecentMessages(arg1:number):Promise<Array<Record<string, any>>>;

export function GetViewerCount(arg1:string):Promise<number>;

export function RemoveChannel(arg1:string):Promise<void>;
